language: node_js
node_js:
  - 'lts/*'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm run clean
  - npm run build:storybook
on:
  branch: master
#deploy:
#  provider: surge
#  skip_cleanup: true
#  domain: https://grommet-resume.surge.sh
#  project: ./dist/storybook
